# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
    # Declare a dependency on the welcome-orb
    welcome: circleci/welcome-orb@0.4.1
jobs:
    write_file:
        docker:
            - image: cimg/base:2020.01
        steps:
            - run: echo start
            - run: echo "written" > ~/val.txt
            - persist_to_workspace:
                  root: ~/
                  paths:
                      - val.txt
    read_file:
        docker:
            - image: cimg/base:2020.01
        steps:
            - run: echo "reading start"
            - attach_workspace:
                at: ~/
            - run: cat ~/val.txt


# Orchestrate or schedule a set of jobs
workflows:
    welcome:
        jobs:
            - write_file
            - read_file:
                requires:
                    - write_file
